# .streamlit/secrets.toml

# Also include your OpenAI key
OPENAI_API_KEY="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"

